# -*- coding: utf-8 -*-
"""enterprise_ml_regression.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pX_N94e9LDCw-QWbCy_B4uWyvsO7d3AB
"""

import pandas as pd
import numpy as np
import os
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import warnings

def analyze_enterprise_regression(
    csv_path,
    target_column="Appointments",
    output_excel="regression_results.xlsx"
):

    # -----------------------------------------------------
    # 1. Load Data
    # -----------------------------------------------------
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"❌ File not found: {csv_path}")

    df = pd.read_csv(csv_path)

    if target_column not in df.columns:
        raise ValueError(f"❌ Target column '{target_column}' not found in CSV.")

    print("📂 Dataset loaded successfully.")
    print(f"Columns: {list(df.columns)}\n")

    # -----------------------------------------------------
    # 2. Identify Feature Columns
    # -----------------------------------------------------
    feature_cols = [c for c in df.columns if c != target_column]

    if len(feature_cols) == 0:
        raise ValueError("❌ No feature columns found besides target.")

    df_features = df[feature_cols]
    df_target = df[target_column]

    # -----------------------------------------------------
    # 3. Detect Column Types
    # -----------------------------------------------------
    numeric_features = df_features.select_dtypes(include=[np.number]).columns.tolist()
    categorical_features = df_features.select_dtypes(exclude=[np.number]).columns.tolist()

    print("🔍 Column Type Detection:")
    print(f" - Numeric Features: {numeric_features}")
    print(f" - Categorical Features: {categorical_features}\n")

    # -----------------------------------------------------
    # 4. Build Preprocessing + Regression Pipeline
    # -----------------------------------------------------
    preprocessor = ColumnTransformer(
        transformers=[
            ("categorical", OneHotEncoder(drop='first'), categorical_features),
            ("numeric", "passthrough", numeric_features)
        ]
    )

    model = Pipeline(steps=[
        ("preprocessing", preprocessor),
        ("regression", LinearRegression())
    ])

    # -----------------------------------------------------
    # 5. Train-Test Split
    # -----------------------------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        df_features, df_target, test_size=0.2, random_state=42
    )

    # -----------------------------------------------------
    # 6. Train Model
    # -----------------------------------------------------
    model.fit(X_train, y_train)
    r2 = model.score(X_test, y_test)

    print(f"📈 Model trained successfully. R² score: {r2:.4f}\n")

    # -----------------------------------------------------
    # 7. Extract Human-Readable Coefficients
    # -----------------------------------------------------
    encoded_feature_names = []

    if categorical_features:
        enc = model.named_steps['preprocessing'].named_transformers_['categorical']
        encoded_feature_names.extend(enc.get_feature_names_out(categorical_features).tolist())

    final_feature_names = numeric_features + encoded_feature_names

    coefficients = model.named_steps['regression'].coef_

    results = pd.DataFrame({
        "Feature": final_feature_names,
        "Appointments Gained per +1 Unit": coefficients,
        "Units Needed per +1 Appointment": [
            (1 / c if c != 0 else np.nan) for c in coefficients
        ]
    })

    print("📊 Regression Coefficients:")
    print(results.to_string(index=False), "\n")

    # -----------------------------------------------------
    # 8. Save to Excel
    # -----------------------------------------------------
    results.to_excel(output_excel, index=False)
    print(f"💾 Results saved to: {output_excel}")

    # -----------------------------------------------------
    # 9. Generate Predictions for Residual Analysis
    # -----------------------------------------------------
    y_pred = model.predict(X_test)
    residuals = y_test - y_pred

    # -----------------------------------------------------
    # 10. Plot 1: Coefficient Impact Bar Chart
    # -----------------------------------------------------
    plt.figure(figsize=(10, 6))
    plt.bar(results["Feature"], results["Appointments Gained per +1 Unit"])
    plt.title("Feature Impact on Appointments")
    plt.xlabel("Features")
    plt.ylabel("Appointments Gained per +1 Unit")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    # -----------------------------------------------------
    # 11. Plot 2A: Predicted vs Actual Scatter
    # -----------------------------------------------------
    plt.figure(figsize=(8, 6))
    plt.scatter(y_test, y_pred)
    plt.xlabel("Actual Appointments")
    plt.ylabel("Predicted Appointments")
    plt.title("Predicted vs Actual")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # -----------------------------------------------------
    # 12. Plot 2B: Residual Distribution Histogram
    # -----------------------------------------------------
    plt.figure(figsize=(8, 6))
    plt.hist(residuals, bins=15, edgecolor='black')
    plt.title("Residual Distribution")
    plt.xlabel("Residual")
    plt.ylabel("Frequency")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    return results, r2, model

results, r2, model = analyze_enterprise_regression(
    csv_path="sample_appointments.csv",
    target_column="Appointments",
    output_excel="regression_results_two.xlsx"
)